site_name: "Documentation"
site_author: fleek.co
site_description: Fleek is a suite of tools with everything you need to build modern sites and apps on the Open Web and its protocols seamlessly.
site_url: https://docs.fleek.co/
copyright: "© 2020 Fleek"
repo_name: fleekhq/fleek-docs
repo_url: https://github.com/fleekhq/fleek-docs
theme:
  name: material
  custom_dir: overrides
  favicon: "./imgs/favicon.ico"
  logo: "./imgs/logo.png"
  font:
    text: "Open Sans"
extra_css:
  - "stylesheets/extra.css"
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Migration to Fleek.xyz: migration/sunsetting-of-fleekco.md
  - IPFS Hosting:
      - Overview: hosting/overview.md
      - Site Deployment: hosting/site-deployment.md
      - Domain Management: domain-management/overview.md
      - Troubleshooting: hosting/troubleshooting.md
  - Internet Computer Hosting:
      - Overview: internet-computer-hosting/overview.md
      - Site Deployment: internet-computer-hosting/site-deployment.md
      - Domain Management: domain-management/custom-dns-domains.md
      - Troubleshooting: internet-computer-hosting/troubleshooting.md
  - Domain Management:
      - Overview: domain-management/overview.md
      - Custom DNS Domains: domain-management/custom-dns-domains.md
      - ENS Domains: domain-management/ens-domains.md
      - HNS Domains: domain-management/hns-domains.md
      - DNSLink: domain-management/dns-link.md
      - Troubleshooting: domain-management/troubleshooting.md
  - Fleek Storage:
      - Overview: storage/overview.md
      - Storage App: storage/storage-app.md
      - Fleek Storage JS: storage/fleek-storage-js.md
      - Custom Storage Domains: storage/custom-storage-domains.md
      - Storage AWS S3 Integration: storage/storage-aws-s3-integration.md
  - IPFS and IC Gateways:
      - Overview: gateways/overview.md
  - Fleek CLI:
      - Overview: fleek-cli/overview.md
      - GitHub Actions: fleek-cli/github-actions.md
  - Fleek API:
      - Overview: fleek-api/overview.md
      - Schema: fleek-api/schema.md
  - Filecoin Archiving:
      - Overview: filecoin-archiving/overview.md
  - Space Daemon:
      - Overview: space-daemon/overview.md
      - Getting Started: space-daemon/getting-started.md
      - Examples: space-daemon/examples.md
      - Security And Cryptography: space-daemon/crypto.md
      - Reset Environment: space-daemon/reset-env.md
  - Space Desktop:
      - Overview: space-desktop/overview.md
  - Space SDK:
      - Overview: space-sdk/overview.md
  - Account Settings:
      - 2FA: settings/2fa.md
  - Tutorials:
      - Hosting: tutorials/hosting.md
      - Storage: tutorials/storage.md
      - Daemon: tutorials/daemon.md
  - Examples:
      - Hosting: examples/hosting.md
      - Storage: examples/storage.md
      - Daemon: examples/daemon.md
  - Knowledge Hub: "https://support.fleek.xyz/hc/en-us"
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FleekHQ
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fleek
    - icon: fontawesome/brands/slack
      link: https://slack.fleek.co/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/fleekhq/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBzlwYM0JjZpjDZ52-SLUmw
